#!/bin/bash
#(c)2017 Alces Software Ltd. HPC Consulting Build Suite
#Job ID: <JOB>
#Cluster: <CLUSTER>

export _ALCES_BASE_HOSTNAME=headnode1
export _ALCES_DOMAIN=cluster.local

#infra,comppute
export _ALCES_PROFILE=infra
export _ALCES_BUILDSERVER=10.50.50.1

export _ALCES_PRVINTERFACE=em1
export _ALCES_PRVNETMASK=255.255.0.0
export _ALCES_PRVNETWORK=10.10.0.0

export _ALCES_MGTINTERFACE=em2
export _ALCES_IBINTERFACE=ib0

export _ALCES_CLUSTER=cluster

export _ALCES_BMC_PASSWORD=A1ce550ftware

export _ALCES_RELAYHOST=mail.alces-software.com

export _ALCES_SSHKEY=tbc

#Get Kennel cmdline options
params=`cat /proc/cmdline`
# Split them on spaces
params_split=(${params// / })
# Go through each of them
for p in "${params_split[@]}"; do
  # And if it's a key value pair
  if [[ $p =~ "=" ]]; then
    # And if the key doesn't have a period in it
    p_split=(${p//=/ })
    if [[ !($p_split[0] =~ ".") ]]; then
      # Then set the key to the value
      eval export $p;
    fi;
  fi
done

export _ALCES_KEYS=`compgen -v | grep _ALCES | while read n; do echo '$'$n; done | xargs`
